### ISSUE TITLE
学识之瓶合不出来

### ISSUE THREAD

**Issue by dalong807** [GuizhanCraft/Slimefun-Wiki#26]
魔法物品里面没有学识之瓶，然后按照合成表在魔法工作台合成学识之瓶时会提示说我没有解锁学识之瓶

**Comment by ybw0014** [comment]
学识之瓶在魔法道具分类中
要合成学识之瓶，你需要在指南书中先解锁才可以合成
该问题不属于Wiki相关，请在你的服务器中提问
