### ISSUE TITLE
外部链接失效

### ISSUE THREAD

**Issue by ybw0014** [GuizhanCraft/Slimefun-Wiki#43]
### 问题描述

外部链接无法直接打开，已确定是docsify的问题 (docsifyjs/docsify#1467)，等待修复。

**Comment by ybw0014** [comment]
已使用plugin暂时修复

**Comment by daoif** [comment]
> 

hi,How did you do it? At present, I am also troubled by this problem

**Comment by ybw0014** [comment]
> > 
> 
> hi,How did you do it? At present, I am also troubled by this problem

By adding a plugin. 

Im lazy to type or copy it. You can view the source code of https://slimefun-wiki.guizhanss.cn/
